name: dependency review
on:
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4.2.2
    - uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803 # v4.8.3
      with:
        config-file: .github/dependency-review-config.yaml
