name: lint
on:
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  lint-go:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2
    - uses: actions/setup-go@78961f6f84d799cd858575bb931c3e51d3b13290 # v5.6.0
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
      with:
        args: --timeout=180s --enable gocritic
  lint-actions:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2
    - uses: docker://rhysd/actionlint:1.7.0@sha256:601d6faeefa07683a4a79f756f430a1850b34d575d734b1d1324692202bf312e # v1.7.0
      with:
        args: -color
